# Generated by Django 4.2.21 on 2025-05-19 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_testseri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HumanResourcesManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=18, null=True)),
                ('color_code', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_deleted'], name='HumanResour_is_dele_464793_idx'), models.Index(fields=['deleted_at'], name='HumanResour_deleted_5becf8_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('mission_type', models.CharField(blank=True, choices=[('inside', 'Inside'), ('outside', 'Outside')], max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_time_to_start', models.DateTimeField(blank=True, null=True)),
                ('date_time_to_end', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vehicle', models.CharField(blank=True, max_length=30, null=True)),
                ('leave_type', models.CharField(blank=True, choices=[('daily_leave', 'Daily Leave'), ('sick_leave', 'Sick Leave'), ('unpaid_leave', 'Unpaid Leave'), ('incentive_leave', 'Incentive Leave'), ('emergency_leave', 'Emergency leave'), ('hourly_leave', 'Hourly Leave')], max_length=30, null=True)),
                ('request_type', models.CharField(choices=[('leave', 'Leave'), ('administrative_mission', 'Administrative Mission')], default='leave', max_length=30)),
                ('reason_for_leave', models.TextField(null=True)),
                ('start_date_at', models.DateField(null=True)),
                ('end_date_at', models.DateField(null=True)),
                ('hourly_leave_date', models.DateField(null=True)),
                ('time_to_start', models.TimeField(null=True)),
                ('time_to_end', models.TimeField(null=True)),
                ('doctor_name', models.CharField(max_length=20, null=True)),
                ('name_of_treatment_center', models.CharField(max_length=255, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city')),
                ('doctor_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_doc', to='core.mainfile')),
                ('leave_file_documents', models.ManyToManyField(related_name='leave_docs', to='core.mainfile')),
                ('requesting_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_requesting', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_deleted'], name='HumanResour_is_dele_cb3f97_idx'), models.Index(fields=['deleted_at'], name='HumanResour_deleted_7e96d0_idx')],
            },
        ),
    ]
