# Generated by Django 4.2.21 on 2025-05-20 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResourcesManager', '0002_category_employeerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=18, null=True)),
                ('color_code', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HumanResourcesManager.folder')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RenameField(
            model_name='employeerequest',
            old_name='date_time_to_end',
            new_name='date_time_to_end_at',
        ),
        migrations.RenameField(
            model_name='employeerequest',
            old_name='date_time_to_start',
            new_name='date_time_to_start_at',
        ),
        migrations.RenameField(
            model_name='employeerequest',
            old_name='time_to_end',
            new_name='time_to_end_at',
        ),
        migrations.RenameField(
            model_name='employeerequest',
            old_name='time_to_start',
            new_name='time_to_start_at',
        ),
        migrations.AddField(
            model_name='employeerequest',
            name='emergency_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeerequest',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HumanResourcesManager.folder'),
        ),
        migrations.AddField(
            model_name='employeerequest',
            name='incentive_leave_date_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employeerequest',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employeerequest',
            name='folder_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HumanResourcesManager.foldercategory'),
        ),
        migrations.AddIndex(
            model_name='foldercategory',
            index=models.Index(fields=['is_deleted'], name='HumanResour_is_dele_00d15e_idx'),
        ),
        migrations.AddIndex(
            model_name='foldercategory',
            index=models.Index(fields=['deleted_at'], name='HumanResour_deleted_8d44e9_idx'),
        ),
    ]
