# Generated by Django 4.2.21 on 2025-05-22 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_country'),
        ('HumanResourcesManager', '0003_foldercategory_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerequest',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country'),
        ),
    ]
