# Generated by Django 4.2.21 on 2025-05-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResourcesManager', '0004_employeerequest_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerequest',
            name='incentive_leave_date_at',
        ),
    ]
