# Generated by Django 4.2.21 on 2025-05-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResourcesManager', '0005_remove_employeerequest_incentive_leave_date_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerequest',
            name='model',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employeerequest',
            name='reason_for_resources',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerequest',
            name='resource_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerequest',
            name='resource_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='request_type',
            field=models.CharField(choices=[('leave', 'Leave'), ('administrative_mission', 'Administrative Mission'), ('resources', 'Resources')], default='leave', max_length=30),
        ),
    ]
