# Generated by Django 4.2.21 on 2025-05-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResourcesManager', '0006_employeerequest_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerequest',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
