# Generated by Django 5.1 on 2024-11-16 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalletManager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=0, help_text='Price in Tomans', max_digits=20)),
                ('trans_action_status', models.CharField(choices=[('deposit', 'DEPOSIT'), ('decrease', 'DECREASE')], max_length=60, null=True)),
                ('total_gb', models.IntegerField(default=0)),
                ('total_user', models.IntegerField(default=0)),
                ('total_sms', models.IntegerField(default=0)),
                ('user_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
