# Generated by Django 5.1 on 2024-12-14 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalletManager', '0002_wallettransaction'),
        ('WorkSpaceManager', '0018_workspacemember_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user_account',
        ),
        migrations.AddField(
            model_name='wallet',
            name='workspace',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkSpaceManager.workspace'),
        ),
    ]
