# Generated by Django 5.1 on 2025-01-05 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalletManager', '0003_remove_wallet_user_account_wallet_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='user_account',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WalletManager.wallet'),
        ),
    ]
