# Generated by Django 5.1 on 2025-01-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalletManager', '0005_wallettransaction_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='ref_number',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
