# Generated by Django 5.1 on 2025-02-12 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalletManager', '0006_wallettransaction_ref_number'),
        ('WorkSpaceManager', '0026_workspacemember_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='workspace',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='WorkSpaceManager.workspace'),
        ),
    ]
