# Generated by Django 5.1.6 on 2025-04-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalletManager', '0008_wallettransaction_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='payment_method',
            field=models.CharField(choices=[('WALLET', 'wallet'), ('PLAN', 'plan')], default='wallet', max_length=30),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='plan_method',
            field=models.CharField(choices=[('startup', 'STARTUP'), ('launching', 'LUNCHING'), ('growth', 'GROWTH'), ('professional', 'PROFESSIONAL')], max_length=30, null=True),
        ),
    ]
