# Generated by Django 5.1.6 on 2025-04-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalletManager', '0010_alter_wallettransaction_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
