# Generated by Django 5.1 on 2025-04-12 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalletManager', '0011_datetest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='plan_method',
            field=models.CharField(choices=[('startup', 'STARTUP'), ('launching', 'LUNCHING'), ('growth', 'GROWTH'), ('professional', 'PROFESSIONAL'), ('magician', 'MAHICIAN'), ('ruby', 'RUBY'), ('diamond', 'DIAMOND'), ('star', 'STAR')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('percentage', models.IntegerField(default=50)),
                ('code', models.CharField(max_length=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_deleted'], name='WalletManag_is_dele_d277f5_idx'), models.Index(fields=['deleted_at'], name='WalletManag_deleted_97156c_idx')],
            },
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WalletManager.discount'),
        ),
    ]
