version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    command: gunicorn your_project.wsgi:application --bind 0.0.0.0:8030
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8030:8030"
#    env_file:
#      - .env
    depends_on:
      - redis

  asgi:
    build: .
    command: daphne -b 0.0.0.0 -p 8040 your_project.asgi:application
    ports:
      - "8040:8040"
#    env_file:
#      - .env
    depends_on:
      - redis

  celery_worker:
    build: .
    command: celery -A your_project worker --loglevel=info
#    env_file:
#      - .env
    depends_on:
      - redis

  celery_beat:
    build: .
    command: celery -A your_project beat --loglevel=info
#    env_file:
#      - .env
    depends_on:
      - redis
      - celery_worker

volumes:
  redis_data: