# Generated by Django 5.1 on 2024-11-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Bermooda/Files')),
                ('its_blong', models.BooleanField(default=False)),
            ],
        ),
    ]
