# Generated by Django 5.1 on 2024-11-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mainfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainfile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mainfile',
            name='workspace_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mainfile',
            name='file',
            field=models.FileField(null=True, upload_to='Bermooda/Files'),
        ),
    ]
