# Generated by Django 5.1.6 on 2025-03-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('last_version', models.CharField(max_length=20)),
                ('is_force', models.BooleanField(default=False)),
                ('cafe_bazar_link', models.URLField(null=True)),
                ('myket_link', models.URLField(null=True)),
                ('download_link', models.URLField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_deleted'], name='core_appupd_is_dele_48778e_idx'), models.Index(fields=['deleted_at'], name='core_appupd_deleted_eac6b0_idx')],
            },
        ),
    ]
