# Generated by Django 5.1 on 2025-04-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_studycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainfile',
            name='original_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
