# Generated by Django 5.1 on 2025-04-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='sub_title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
