# Generated by Django 5.1 on 2025-04-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reminder_sub_title_reminder_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='remind_at',
            field=models.DateTimeField(null=True),
        ),
    ]
