# Generated by Django 4.2.21 on 2025-05-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_reminder_remind_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_at', models.DateField(null=True)),
            ],
        ),
    ]
