# Generated by Django 4.2.21 on 2025-05-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_testseri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testseri',
            name='date_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
