# Generated by Django 4.2.21 on 2025-05-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.IntegerField(null=True),
        ),
    ]
