# Generated by Django 5.1 on 2024-10-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0001_initial'),
        ('WorkSpaceManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='category_customer',
            field=models.ManyToManyField(related_name='category_workspace', to='CrmCore.category'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='label_customer',
            field=models.ManyToManyField(related_name='workspace_label', to='CrmCore.label'),
        ),
    ]
