# Generated by Django 5.1 on 2024-10-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0001_initial'),
        ('WorkSpaceManager', '0002_workspace_category_customer_workspace_label_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='customers',
            field=models.ManyToManyField(related_name='workspace_customer', to='CrmCore.customeruser'),
        ),
    ]
