# Generated by Django 5.1 on 2024-10-28 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0001_initial'),
        ('WorkSpaceManager', '0003_workspace_customers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='category_customer',
            field=models.ManyToManyField(blank=True, related_name='category_workspace', to='CrmCore.category'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='workspace_customer', to='CrmCore.customeruser'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='label_customer',
            field=models.ManyToManyField(blank=True, related_name='workspace_label', to='CrmCore.label'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='workspace_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
