# Generated by Django 5.1 on 2024-10-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0002_remove_project_owner'),
        ('WorkSpaceManager', '0004_alter_workspace_category_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='project',
            field=models.ManyToManyField(related_name='workspace_project', to='ProjectManager.project'),
        ),
    ]
