# Generated by Django 5.1 on 2024-10-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailManager', '0001_initial'),
        ('WorkSpaceManager', '0005_workspace_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='conversation',
            field=models.ManyToManyField(to='MailManager.conversation'),
        ),
    ]
