# Generated by Django 5.1 on 2024-10-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0006_workspace_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='conversation',
        ),
    ]
