# Generated by Django 5.1 on 2024-11-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0008_alter_workspace_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='category_customer',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='label_customer',
        ),
    ]
