# Generated by Django 5.1 on 2024-11-23 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0009_remove_workspace_category_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='project',
        ),
    ]
