# Generated by Django 5.1 on 2024-11-25 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0011_remove_workspace_member_workspacemember'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='brand_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='business_detail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='business_type',
            field=models.CharField(choices=[('کسب کار آنلاین', 'کسب کار آنلاین '), ('کسب کار آفلاین', 'کسب کار آفلاین '), ('هر دو', 'هر دو')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='economic_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='fullname',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='national_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='personal_type',
            field=models.CharField(choices=[('حقیقی', 'حقیقی'), ('حقوقی', 'حقوقی')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='reference_category',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workspace',
            name='reference_sub_category',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workspace',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='WorkSpaceManager.workspace')),
            ],
        ),
    ]
