# Generated by Django 5.1 on 2024-11-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0012_workspace_brand_name_workspace_business_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='jadoo_brand_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='brand_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
