# Generated by Django 5.1 on 2024-11-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0013_workspace_jadoo_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='economic_code',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='national_code',
            field=models.BigIntegerField(null=True),
        ),
    ]
