# Generated by Django 5.1 on 2024-12-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0014_workspace_is_authenticated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='economic_code',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='email',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='national_code',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='personal_type',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='phone_number',
        ),
    ]
