# Generated by Django 5.1 on 2024-12-01 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0015_remove_workspace_brand_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=400, null=True)),
                ('title', models.CharField(max_length=50)),
                ('icon', models.URLField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('isDisable', models.BooleanField(default=False)),
                ('isMedia', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='workspace',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WorkSpaceManager.maincategory'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=400, null=True)),
                ('title', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=200, null=True)),
                ('isDisable', models.IntegerField(null=True)),
                ('isMedia', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('main_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='WorkSpaceManager.maincategory')),
            ],
        ),
        migrations.AddField(
            model_name='workspace',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WorkSpaceManager.subcategory'),
        ),
    ]
