# Generated by Django 5.1 on 2024-12-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0017_workspace_avatar_workspacemember_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='fullname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
