# Generated by Django 5.1 on 2025-01-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0019_workspace_jadoo_workspace_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
