# Generated by Django 5.1 on 2025-01-21 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0020_workspace_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('manager', 'MANAGER'), ('expert', 'EXPERT'), ('no access', 'NO ACCESS')], default='no access', max_length=60)),
                ('member', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkSpaceManager.workspacemember')),
            ],
        ),
        migrations.CreateModel(
            name='ViewName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=200, null=True)),
                ('permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_names', to='WorkSpaceManager.memberpermission')),
            ],
        ),
        migrations.CreateModel(
            name='MethodPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(choices=[('get', 'GET'), ('post', 'POST'), ('delete', 'DELETE'), ('put', 'PUT')], max_length=55, null=True)),
                ('is_permission', models.BooleanField(default=False)),
                ('view', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='WorkSpaceManager.viewname')),
            ],
        ),
    ]
