# Generated by Django 5.1 on 2025-01-21 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0021_memberpermission_viewname_methodpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpermission',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkSpaceManager.workspacemember'),
        ),
    ]
