# Generated by Django 5.1 on 2025-01-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0022_alter_memberpermission_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpermission',
            name='permission_name',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
