# Generated by Django 5.1 on 2025-01-26 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0023_memberpermission_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpermission',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='WorkSpaceManager.workspacemember'),
        ),
    ]
