# Generated by Django 5.1 on 2025-02-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0025_workspace_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='is_accepted',
            field=models.BooleanField(default=True),
        ),
    ]
