# Generated by Django 5.1 on 2025-02-16 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0027_workspacemember_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrialActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('refrence_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='workspace',
            name='industrialactivity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WorkSpaceManager.industrialactivity'),
        ),
        migrations.DeleteModel(
            name='MainCategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
