# Generated by Django 5.1 on 2025-02-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0028_industrialactivity_remove_workspace_main_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='first_name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='last_name',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
