# Generated by Django 5.1 on 2025-02-19 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0029_workspacemember_first_name_workspacemember_last_name'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='workspace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['is_deleted'], name='WorkSpaceMa_is_dele_98a05e_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['deleted_at'], name='WorkSpaceMa_deleted_f607fc_idx'),
        ),
    ]
