# Generated by Django 5.1 on 2025-02-19 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0030_alter_workspace_options_workspace_created_at_and_more'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industrialactivity',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='memberpermission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='methodpermission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='viewname',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='workspacemember',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='industrialactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='industrialactivity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='industrialactivity',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='industrialactivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='link',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='link',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='link',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='memberpermission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='memberpermission',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='memberpermission',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='memberpermission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='methodpermission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='methodpermission',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='methodpermission',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='methodpermission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='viewname',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='viewname',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='viewname',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='viewname',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='industrialactivity',
            index=models.Index(fields=['is_deleted'], name='WorkSpaceMa_is_dele_8549b1_idx'),
        ),
        migrations.AddIndex(
            model_name='industrialactivity',
            index=models.Index(fields=['deleted_at'], name='WorkSpaceMa_deleted_751913_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['is_deleted'], name='WorkSpaceMa_is_dele_0ac289_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['deleted_at'], name='WorkSpaceMa_deleted_985ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='memberpermission',
            index=models.Index(fields=['is_deleted'], name='WorkSpaceMa_is_dele_e0568f_idx'),
        ),
        migrations.AddIndex(
            model_name='memberpermission',
            index=models.Index(fields=['deleted_at'], name='WorkSpaceMa_deleted_75f564_idx'),
        ),
        migrations.AddIndex(
            model_name='methodpermission',
            index=models.Index(fields=['is_deleted'], name='WorkSpaceMa_is_dele_496cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='methodpermission',
            index=models.Index(fields=['deleted_at'], name='WorkSpaceMa_deleted_9818e2_idx'),
        ),
        migrations.AddIndex(
            model_name='viewname',
            index=models.Index(fields=['is_deleted'], name='WorkSpaceMa_is_dele_c1368b_idx'),
        ),
        migrations.AddIndex(
            model_name='viewname',
            index=models.Index(fields=['deleted_at'], name='WorkSpaceMa_deleted_e291e7_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemember',
            index=models.Index(fields=['is_deleted'], name='WorkSpaceMa_is_dele_d95198_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemember',
            index=models.Index(fields=['deleted_at'], name='WorkSpaceMa_deleted_c76385_idx'),
        ),
    ]
