# Generated by Django 5.1 on 2025-02-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0031_alter_industrialactivity_options_alter_link_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
