# Generated by Django 5.1.6 on 2025-02-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0032_alter_workspace_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='jadoo_brand_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
