# Generated by Django 5.1.6 on 2025-03-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0033_alter_workspace_jadoo_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='is_team_bonos',
            field=models.BooleanField(default=False),
        ),
    ]
