# Generated by Django 5.1.6 on 2025-03-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0034_workspace_is_team_bonos'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='jadoo_member_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
