# Generated by Django 5.1.6 on 2025-03-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0035_workspacemember_jadoo_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='business_employer',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
