# Generated by Django 5.1.6 on 2025-03-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0036_workspace_business_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='bank_number',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='economic_number',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='fax_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='national_code',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='person_type',
            field=models.CharField(choices=[('person', 'PERSON'), ('legal', 'LEGAL')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='personal_information_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='postal_code',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='tel_number',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
