# Generated by Django 5.1.6 on 2025-03-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0037_workspace_address_workspace_bank_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='crm_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='group_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='marketing_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='project_board_status',
            field=models.BooleanField(default=False),
        ),
    ]
