# Generated by Django 5.1.6 on 2025-03-09 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0038_workspace_crm_status_workspace_group_chat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='crm_status',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='group_chat',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='marketing_status',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='project_board_status',
        ),
        migrations.CreateModel(
            name='WorkSpacePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('permission_type', models.CharField(max_length=50, null=True)),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='WorkSpaceManager.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_deleted'], name='WorkSpaceMa_is_dele_ff77bc_idx'), models.Index(fields=['deleted_at'], name='WorkSpaceMa_deleted_049d54_idx')],
            },
        ),
    ]
