# Generated by Django 5.1.6 on 2025-03-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0039_remove_workspace_crm_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='company_name',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
