# Generated by Django 5.1.6 on 2025-03-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0041_remove_workspacemember_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacepermission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
