# Generated by Django 5.1.6 on 2025-03-18 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0042_workspacepermission_is_active'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='document_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duc_image', to='core.mainfile'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='national_card_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='national_image', to='core.mainfile'),
        ),
    ]
