# Generated by Django 5.1.6 on 2025-04-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0043_workspace_document_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='payment_method',
            field=models.CharField(choices=[('WALLET', 'wallet'), ('PLAN', 'plan')], default='wallet', max_length=30),
        ),
        migrations.AddField(
            model_name='workspace',
            name='plan_method',
            field=models.CharField(choices=[('startup', 'STARTUP'), ('launching', 'LUNCHING'), ('growth', 'GROWTH'), ('professional', 'PROFESSIONAL')], max_length=30, null=True),
        ),
    ]
