# Generated by Django 5.1.6 on 2025-04-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0044_workspace_payment_method_workspace_plan_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='plan_started_date',
            field=models.DateTimeField(null=True),
        ),
    ]
