# Generated by Django 5.1 on 2025-04-16 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0045_workspace_plan_started_date'),
        ('core', '0007_appupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='bad_record_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='certificate_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city'),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='contract_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='date_of_start_to_work',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='employee_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='insurance_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='marriage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='more_information',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='national_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='number_of_children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='postal_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='shaba_number',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state'),
        ),
    ]
