# Generated by Django 5.1 on 2025-04-16 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0046_workspacemember_address_and_more'),
        ('core', '0008_studycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='study_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.studycategory'),
        ),
    ]
