# Generated by Django 5.1 on 2025-04-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0047_workspacemember_study_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='job_position',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
