# Generated by Django 5.1 on 2025-04-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0050_remove_workspacemember_bad_record_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemember',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='contract_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='date_of_start_to_work',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='job_position',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='number_of_children',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='shaba_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
