# Generated by Django 5.1 on 2025-04-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0051_alter_workspacemember_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
