# Generated by Django 5.1 on 2025-04-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0052_alter_workspacemember_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='education_type',
            field=models.CharField(blank=True, choices=[('highschool', 'HIGHSCHOOL'), ('associate', 'ASSOCIATE'), ('bachelor', 'BACHELOR'), ('master', 'MASTER'), ('phd', 'PHD')], max_length=55, null=True),
        ),
    ]
