# Generated by Django 5.1.6 on 2025-04-29 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0054_alter_workspace_title'),
        ('core', '0012_reminder_remind_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacemember',
            name='bad_records',
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='bad_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_bad_record', to='core.mainfile'),
        ),
    ]
