# Generated by Django 5.1 on 2025-05-06 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0055_remove_workspacemember_bad_records_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('fulltime', 'FullTime'), ('parttime', 'PartTime'), ('remote', 'Remote'), ('contract', 'Contract'), ('internship', 'InternShip'), ('hourly', 'Hourly')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='personal_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('hourly', 'Hourly'), ('per_project', 'PerProject'), ('commission_based', 'CommissionBased'), ('negotiable', 'Nagotiable'), ('base_commission', 'BaseCommission')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=15, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='WorkSpaceManager.workspacemember')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_deleted'], name='WorkSpaceMa_is_dele_bf8e4b_idx'), models.Index(fields=['deleted_at'], name='WorkSpaceMa_deleted_c7e56a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=15, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='WorkSpaceManager.workspacemember')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_deleted'], name='WorkSpaceMa_is_dele_d16e37_idx'), models.Index(fields=['deleted_at'], name='WorkSpaceMa_deleted_3a7854_idx')],
            },
        ),
    ]
