# Generated by Django 5.1.6 on 2025-05-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0056_workspacemember_employment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemember',
            name='personal_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
