# Generated by Django 5.1 on 2025-05-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0057_alter_workspacemember_personal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='is_auth_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
