# Generated by Django 5.1.6 on 2025-05-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0058_workspace_is_auth_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='auth_status',
            field=models.CharField(blank=True, choices=[('is_pending', 'IsPending'), ('is_accepted', 'IsAccepted'), ('is_rejected', 'IsRejected')], default='is_rejected', max_length=20, null=True),
        ),
    ]
