# Generated by Django 5.1.6 on 2025-05-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0059_workspace_auth_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='auth_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='rejected', max_length=20, null=True),
        ),
    ]
