# Generated by Django 4.2.21 on 2025-05-24 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResourcesManager', '0005_remove_employeerequest_incentive_leave_date_at'),
        ('WorkSpaceManager', '0060_alter_workspace_auth_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder_members', to='HumanResourcesManager.folder'),
        ),
    ]
