# Generated by Django 4.2.21 on 2025-05-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceManager', '0061_workspacemember_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='user_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], default='member', max_length=11, null=True),
        ),
    ]
