# Generated by Django 5.1 on 2024-10-28 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CrmCore', '0001_initial'),
        ('core', '0002_city_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JadooToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReadyText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilterTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, null=True)),
                ('filter', models.ManyToManyField(to='UserManager.filter')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=70, unique=True)),
                ('personal_type', models.CharField(choices=[('حقیقی', 'حقیقی'), ('حقوقی', 'حقوقی')], max_length=9)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('app_username', models.CharField(max_length=55, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('verify_code', models.CharField(max_length=10, null=True)),
                ('is_super_manager', models.BooleanField(default=False)),
                ('current_ip_address', models.CharField(max_length=70, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city')),
                ('customer', models.ManyToManyField(to='CrmCore.customeruser')),
                ('ready_text', models.ManyToManyField(to='UserManager.readytext')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
