# Generated by Django 5.1 on 2024-10-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='app_username',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
