# Generated by Django 5.1 on 2024-10-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0004_alter_category_title'),
        ('UserManager', '0004_alter_useraccount_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='customer',
            field=models.ManyToManyField(blank=True, to='CrmCore.customeruser'),
        ),
    ]
