# Generated by Django 5.1 on 2024-11-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0005_alter_useraccount_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_register',
            field=models.BooleanField(default=False),
        ),
    ]
