# Generated by Django 5.1 on 2024-11-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0006_useraccount_is_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=70, null=True, unique=True),
        ),
    ]
