# Generated by Django 5.1 on 2024-11-07 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0007_alter_useraccount_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readytext',
            options={'permissions': [('read_product', 'Can read Product'), ('edit_product', 'Can edit Product'), ('delete_product', 'Can delete Product'), ('create_product', 'Can create Product')]},
        ),
    ]
