# Generated by Django 5.1 on 2024-11-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0009_role_useraccount_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readytext',
            options={'permissions': [('ساخت یک تکست', 'Can read Product'), ('edit_product', 'Can edit Product'), ('delete_product', 'Can delete Product'), ('create_product', 'Can create Product')]},
        ),
    ]
