# Generated by Django 5.1 on 2024-11-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0010_alter_readytext_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='role',
        ),
        migrations.AlterModelOptions(
            name='readytext',
            options={},
        ),
        migrations.CreateModel(
            name='PermissionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, null=True)),
                ('group_obj', models.ManyToManyField(to='auth.group')),
            ],
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
