# Generated by Django 5.1 on 2024-11-08 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0013_remove_permissiontype_requset_type_perm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissioncategory',
            name='class_name',
        ),
        migrations.CreateModel(
            name='ViewName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, null=True)),
                ('perm_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_names', to='UserManager.permissioncategory')),
            ],
        ),
    ]
