# Generated by Django 5.1 on 2024-11-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0014_remove_permissioncategory_class_name_viewname'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewname',
            name='nessery_manager',
            field=models.BooleanField(default=False),
        ),
    ]
