# Generated by Django 5.1 on 2024-11-08 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0015_viewname_nessery_manager'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('group_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.AlterField(
            model_name='permissioncategory',
            name='group_obj',
            field=models.ManyToManyField(to='UserManager.groupmain'),
        ),
        migrations.AlterField(
            model_name='permissiontype',
            name='group_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gp_perm_type', to='UserManager.groupmain'),
        ),
    ]
