# Generated by Django 5.1 on 2024-11-08 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0016_groupmain_alter_permissioncategory_group_obj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiontype',
            name='group_obj',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gp_perm_type', to='UserManager.groupmain'),
        ),
    ]
