# Generated by Django 5.1 on 2024-11-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0017_alter_permissiontype_group_obj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmain',
            old_name='group_obj',
            new_name='real_group_obj',
        ),
    ]
