# Generated by Django 5.1 on 2024-11-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0019_useraccount_groups_useraccount_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='permissiontype',
            name='permission_type',
            field=models.CharField(choices=[('read', 'READ'), ('edit', 'EDIT'), ('manager', 'MANAGER'), ('notaccses', 'NOTACCSES')], max_length=40, null=True),
        ),
    ]
