# Generated by Django 5.1 on 2024-11-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0021_alter_useraccount_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='slug',
        ),
    ]
