# Generated by Django 5.1 on 2024-11-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0022_remove_useraccount_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
