# Generated by Django 5.1 on 2024-11-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0023_useraccount_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='slug',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone_incripted',
            field=models.TextField(null=True),
        ),
    ]
