# Generated by Django 5.1 on 2024-11-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0024_remove_useraccount_slug_useraccount_phone_incripted'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissioncategory',
            name='workspace',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
