# Generated by Django 5.1 on 2024-11-13 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0025_permissioncategory_workspace'),
        ('core', '0005_mainfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mainfile'),
        ),
    ]
