# Generated by Django 5.1 on 2024-11-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0026_useraccount_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_profile',
            field=models.BooleanField(default=False),
        ),
    ]
