# Generated by Django 5.1 on 2024-11-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0027_useraccount_is_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='current_workspace_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
