# Generated by Django 5.1 on 2024-11-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0029_remove_useraccount_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='expire_verify_code',
            field=models.TimeField(null=True),
        ),
    ]
