# Generated by Django 5.1 on 2024-11-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0030_useraccount_expire_verify_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='refrence_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='refrence_token',
            field=models.TextField(null=True),
        ),
    ]
