# Generated by Django 5.1 on 2024-11-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0031_useraccount_refrence_id_useraccount_refrence_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissioncategory',
            name='real_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
