# Generated by Django 5.1 on 2024-11-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0032_permissioncategory_real_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
