# Generated by Django 5.1 on 2024-11-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0033_alter_useraccount_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='fcm_token',
            field=models.TextField(null=True),
        ),
    ]
