# Generated by Django 5.1 on 2024-12-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0034_useraccount_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='brand_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='economic_code',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='fcm_token_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='fullname',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='national_code',
            field=models.BigIntegerField(null=True),
        ),
    ]
