# Generated by Django 5.1 on 2024-12-15 18:20

import UserManager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0035_remove_useraccount_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='fcm_token',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='fcm_token_status',
        ),
        migrations.CreateModel(
            name='FcmToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_account', models.ForeignKey(null=True, on_delete=UserManager.models.UserAccount, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
