# Generated by Django 5.1 on 2025-01-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0037_fcmtoken_token_alter_fcmtoken_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_auth',
            field=models.BooleanField(default=False),
        ),
    ]
