# Generated by Django 5.1 on 2025-02-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0039_readytext_owner_readytext_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonosPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_bonos',
            field=models.BooleanField(default=True),
        ),
    ]
