# Generated by Django 5.1 on 2025-02-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0040_bonosphone_useraccount_is_bonos'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='fake_name',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
