# Generated by Django 5.1 on 2025-02-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0041_useraccount_fake_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='current_workspace_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
