# Generated by Django 5.1.6 on 2025-03-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0044_alter_useraccount_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmtoken',
            name='is_application',
            field=models.BooleanField(default=False),
        ),
    ]
