# Generated by Django 5.1.6 on 2025-04-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0045_fcmtoken_is_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
