# Generated by Django 5.1 on 2025-05-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0046_useraccount_online_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='register_at',
            field=models.DateTimeField(null=True),
        ),
    ]
