# Generated by Django 5.1 on 2025-05-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0047_useraccount_register_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='sms_q',
            field=models.IntegerField(default=0),
        ),
    ]
