# Generated by Django 5.1 on 2025-05-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0048_useraccount_sms_q'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='sms_q',
            field=models.IntegerField(default=-1),
        ),
    ]
