# Generated by Django 4.2.21 on 2025-05-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0049_alter_useraccount_sms_q'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('otp', models.CharField(max_length=6, null=True)),
                ('created_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
