# Generated by Django 4.2.21 on 2025-05-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0050_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
