# Generated by Django 5.1 on 2025-01-12 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaningManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_title', models.CharField(max_length=70, null=True)),
                ('label_color_code', models.CharField(max_length=70, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('remember_date', models.CharField(max_length=200, null=True)),
                ('reaped_status', models.BooleanField(default=False)),
                ('description', models.TextField(null=True)),
                ('more_information', models.BooleanField(default=False)),
                ('date_to_start', models.CharField(max_length=200, null=True)),
                ('date_to_end', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True)),
                ('planing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PlaningManager.planingmanager')),
            ],
        ),
    ]
