# Generated by Django 5.1 on 2025-01-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlaningManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaningManager',
            new_name='Planing',
        ),
    ]
