# Generated by Django 5.1 on 2025-01-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaningManager', '0002_rename_planingmanager_planing'),
    ]

    operations = [
        migrations.AddField(
            model_name='planing',
            name='date_to_calender',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
