# Generated by Django 5.1 on 2025-01-12 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaningManager', '0003_planing_date_to_calender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='planing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='PlaningManager.planing'),
        ),
    ]
