# Generated by Django 5.1 on 2025-01-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaningManager', '0005_planing_created_planing_creator_planing_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='planing',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
