# Generated by Django 5.1 on 2025-01-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlaningManager', '0006_planing_activated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planing',
            old_name='date_to_calender',
            new_name='date_in_calender',
        ),
    ]
