# Generated by Django 5.1 on 2025-01-12 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaningManager', '0007_rename_date_to_calender_planing_date_in_calender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planing',
            name='activated',
        ),
        migrations.CreateModel(
            name='InvitedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=False)),
                ('planing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_users', to='PlaningManager.planing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RangeDateCalender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=200, null=True)),
                ('end_date', models.CharField(max_length=200, null=True)),
                ('planing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='range_date_calenders', to='PlaningManager.planing')),
            ],
        ),
    ]
