# Generated by Django 5.1 on 2025-01-13 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaningManager', '0008_remove_planing_activated_inviteduser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rangedatecalender',
            name='planing',
        ),
        migrations.AddField(
            model_name='planing',
            name='range_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='range_date_calenders', to='PlaningManager.rangedatecalender'),
        ),
    ]
