# Generated by Django 5.1 on 2025-01-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaningManager', '0009_remove_rangedatecalender_planing_planing_range_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rangedatecalender',
            name='end_date',
        ),
        migrations.AddField(
            model_name='rangedatecalender',
            name='reaped_type',
            field=models.CharField(choices=[('weekly', 'WEEKLY'), ('daily', 'DAILY'), ('monthly', 'MONTHLY')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planing',
            name='date_to_end',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='planing',
            name='date_to_start',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='planing',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
