# Generated by Django 5.1 on 2025-01-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaningManager', '0011_email_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangedatecalender',
            name='reaped_type',
            field=models.CharField(choices=[('weekly', 'WEEKLY'), ('daily', 'DAILY'), ('monthly', 'MONTHLY'), ('no_repetition', 'NO_REPETITION')], max_length=100, null=True),
        ),
    ]
