# Generated by Django 5.1 on 2025-01-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaningManager', '0012_alter_rangedatecalender_reaped_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='planing',
            name='remember_type',
            field=models.CharField(blank=True, choices=[('hour', 'HOUR'), ('minute', 'MINUTE'), ('day', 'day')], max_length=80, null=True),
        ),
    ]
