# Generated by Django 5.1 on 2025-01-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaningManager', '0013_planing_remember_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
