# Generated by Django 5.1 on 2025-01-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaningManager', '0014_alter_planing_description'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planing',
            name='files',
            field=models.ManyToManyField(to='core.mainfile'),
        ),
        migrations.AlterField(
            model_name='planing',
            name='remember_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
