# Generated by Django 5.1 on 2025-02-02 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaningManager', '0016_alter_inviteduser_planing_alter_inviteduser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderPlanTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(max_length=100, null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PlaningManager.planing')),
            ],
        ),
    ]
