# Generated by Django 5.1 on 2025-02-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaningManager', '0017_reminderplantime'),
    ]

    operations = [
        migrations.AddField(
            model_name='planing',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
