# Generated by Django 5.1 on 2025-02-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlaningManager', '0018_planing_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planing',
            name='name',
        ),
    ]
