# Generated by Django 5.1.6 on 2025-03-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0004_notification_side_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sub_title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
