# Generated by Django 5.1.6 on 2025-04-12 05:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CalenderManager', '0003_alter_meetingemail_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeetingMembers',
            new_name='MeetingMember',
        ),
        migrations.RenameIndex(
            model_name='meetingmember',
            new_name='CalenderMan_is_dele_dbf7e0_idx',
            old_name='CalenderMan_is_dele_3fceae_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingmember',
            new_name='CalenderMan_deleted_4057e3_idx',
            old_name='CalenderMan_deleted_80f4dd_idx',
        ),
    ]
