# Generated by Django 5.1.6 on 2025-04-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalenderManager', '0004_rename_meetingmembers_meetingmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='end_meeting_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_meeting_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
