# Generated by Django 5.1.6 on 2025-04-12 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalenderManager', '0005_meeting_end_meeting_time_meeting_start_meeting_time'),
        ('WorkSpaceManager', '0045_workspace_plan_started_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=20, null=True)),
                ('color_code', models.CharField(max_length=12, null=True)),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkSpaceManager.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='meeting',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CalenderManager.meetinglabel'),
        ),
        migrations.AddIndex(
            model_name='meetinglabel',
            index=models.Index(fields=['is_deleted'], name='CalenderMan_is_dele_48f802_idx'),
        ),
        migrations.AddIndex(
            model_name='meetinglabel',
            index=models.Index(fields=['deleted_at'], name='CalenderMan_deleted_97a33f_idx'),
        ),
        migrations.DeleteModel(
            name='MetingLabel',
        ),
    ]
