# Generated by Django 5.1 on 2025-04-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalenderManager', '0006_meetinglabel_alter_meeting_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinglabel',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetinglabel',
            name='key_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
