# Generated by Django 5.1 on 2025-04-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalenderManager', '0007_meetinglabel_icon_meetinglabel_key_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinglabel',
            name='titleTr1',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
