# Generated by Django 5.1 on 2025-04-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalenderManager', '0008_meetinglabel_titletr1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='remember_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
