# Generated by Django 5.1 on 2024-11-13 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0001_initial'),
        ('core', '0005_mainfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='logo_main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_logo', to='core.mainfile'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='signature_main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_signature', to='core.mainfile'),
        ),
    ]
