# Generated by Django 5.1 on 2024-11-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0002_invoice_logo_main_invoice_signature_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='signature',
        ),
    ]
