# Generated by Django 5.1 on 2024-11-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0004_alter_invoice_logo_main_alter_invoice_signature_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
