# Generated by Django 5.1.6 on 2025-03-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0006_invoice_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='validity_date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
