# Generated by Django 5.1.6 on 2025-03-08 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0056_customeruser_is_followed'),
        ('CustomerFinance', '0007_invoice_created_date_invoice_validity_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('color_code', models.CharField(blank=True, max_length=30, null=True)),
                ('group_crm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_statuses', to='CrmCore.groupcrm')),
            ],
        ),
    ]
