# Generated by Django 5.1.6 on 2025-03-08 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0008_invoicestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomerFinance.invoicestatus'),
        ),
    ]
