# Generated by Django 5.1.6 on 2025-03-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0056_customeruser_is_followed'),
        ('CustomerFinance', '0009_invoice_status'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='invoicestatus',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productinvoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='information',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='information',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='information',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='information',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='invoicestatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='invoicestatus',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='invoicestatus',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='invoicestatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='productinvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='productinvoice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='productinvoice',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='productinvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='information',
            index=models.Index(fields=['is_deleted'], name='CustomerFin_is_dele_1e204c_idx'),
        ),
        migrations.AddIndex(
            model_name='information',
            index=models.Index(fields=['deleted_at'], name='CustomerFin_deleted_70147b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_deleted'], name='CustomerFin_is_dele_0031d8_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['deleted_at'], name='CustomerFin_deleted_6a3ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicestatus',
            index=models.Index(fields=['is_deleted'], name='CustomerFin_is_dele_dcfb18_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicestatus',
            index=models.Index(fields=['deleted_at'], name='CustomerFin_deleted_206d83_idx'),
        ),
        migrations.AddIndex(
            model_name='productinvoice',
            index=models.Index(fields=['is_deleted'], name='CustomerFin_is_dele_9f947c_idx'),
        ),
        migrations.AddIndex(
            model_name='productinvoice',
            index=models.Index(fields=['deleted_at'], name='CustomerFin_deleted_f944c2_idx'),
        ),
    ]
