# Generated by Django 5.1.6 on 2025-03-09 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0010_alter_information_options_alter_invoice_options_and_more'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_buyer', to='core.state'),
        ),
    ]
