# Generated by Django 5.1.6 on 2025-03-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0011_alter_information_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'CASH'), ('installment', 'INSTALLMENT')], default='cash', max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='productinvoice',
            name='code',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
