# Generated by Django 5.1.6 on 2025-03-09 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0013_invoice_signature_buyer'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='qr_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mainfile'),
        ),
    ]
