# Generated by Django 5.1.6 on 2025-03-10 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0014_alter_invoice_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
