# Generated by Django 5.1.6 on 2025-03-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0015_invoice_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uuid',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
