# Generated by Django 5.1.6 on 2025-03-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0016_alter_invoice_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='uuid',
            new_name='main_id',
        ),
    ]
