# Generated by Django 5.1.6 on 2025-03-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0019_alter_invoice_main_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinvoice',
            name='unit',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
