# Generated by Django 5.1.6 on 2025-03-11 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0058_remove_customeruser_invoice'),
        ('CustomerFinance', '0020_productinvoice_unit'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CrmCore.customeruser'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='installment_count',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('price', models.DecimalField(decimal_places=0, help_text='Price in Tomans', max_digits=20)),
                ('date_to_pay', models.DateField(null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('date_payed', models.DateField(null=True)),
                ('is_delayed', models.BooleanField(default=False)),
                ('document_of_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mainfile')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='CustomerFinance.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_deleted'], name='CustomerFin_is_dele_5e776d_idx'), models.Index(fields=['deleted_at'], name='CustomerFin_deleted_e0cd61_idx')],
            },
        ),
    ]
