# Generated by Django 5.1.6 on 2025-03-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0021_invoice_customer_invoice_installment_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='validity_date',
            field=models.DateField(null=True),
        ),
    ]
