# Generated by Django 5.1.6 on 2025-03-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0022_alter_invoice_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='validity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
