# Generated by Django 5.1.6 on 2025-03-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0023_alter_invoice_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='interest_percentage',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
