# Generated by Django 5.1.6 on 2025-03-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0024_invoice_interest_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('preـinvoice', 'PRE_INVOICE'), ('final_invoice', 'FINAL_INVOICE')], max_length=20, null=True),
        ),
    ]
