# Generated by Django 5.1.6 on 2025-03-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0025_invoice_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('preinvoice', 'PREINVOICE'), ('finalinvoice', 'FINALINVOICE')], max_length=20, null=True),
        ),
    ]
