# Generated by Django 5.1.6 on 2025-03-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0026_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_time_to_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='login_ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='verify_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
