# Generated by Django 5.1.6 on 2025-04-03 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0027_invoice_date_time_to_login_invoice_login_ip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={'ordering': ['date_to_pay']},
        ),
        migrations.AlterModelOptions(
            name='productinvoice',
            options={'ordering': ['id']},
        ),
        migrations.RemoveIndex(
            model_name='installment',
            name='CustomerFin_is_dele_5e776d_idx',
        ),
        migrations.RemoveIndex(
            model_name='installment',
            name='CustomerFin_deleted_e0cd61_idx',
        ),
        migrations.RemoveIndex(
            model_name='productinvoice',
            name='CustomerFin_is_dele_9f947c_idx',
        ),
        migrations.RemoveIndex(
            model_name='productinvoice',
            name='CustomerFin_deleted_f944c2_idx',
        ),
    ]
