# Generated by Django 5.1.6 on 2025-04-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0028_alter_installment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_payed',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_to_pay',
            field=models.DateField(null=True),
        ),
    ]
