# Generated by Django 5.1.6 on 2025-04-09 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0029_invoice_date_payed_invoice_date_to_pay'),
        ('core', '0007_appupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='date_payed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='date_to_pay',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='document_of_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mainfile'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='CustomerFinance.invoice'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='is_delayed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='installment',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='installment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Price in Tomans', max_digits=20),
        ),
    ]
