# Generated by Django 5.1.6 on 2025-04-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0030_alter_installment_date_payed_and_more'),
        ('core', '0007_appupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='document_of_payment',
        ),
        migrations.AddField(
            model_name='installment',
            name='document_of_payment',
            field=models.ManyToManyField(to='core.mainfile'),
        ),
    ]
