# Generated by Django 5.1.6 on 2025-04-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0031_remove_installment_document_of_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
