# Generated by Django 5.1.6 on 2025-04-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0032_installment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='date_payed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
