# Generated by Django 5.1 on 2025-04-13 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerFinance', '0033_alter_installment_date_payed'),
        ('core', '0007_appupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_documents',
            field=models.ManyToManyField(related_name='invoice_documents', to='core.mainfile'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='qr_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_qr_codes', to='core.mainfile'),
        ),
    ]
