# Generated by Django 5.1 on 2024-10-28 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ProjectManager/Tasks')),
            ],
        ),
        migrations.CreateModel(
            name='TaskLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('color_code', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('status', models.BooleanField(default=False)),
                ('date_to_start', models.CharField(max_length=30, null=True)),
                ('time_to_start', models.CharField(max_length=30, null=True)),
                ('date_to_end', models.CharField(max_length=30, null=True)),
                ('time_to_end', models.CharField(max_length=30, null=True)),
                ('check_by_date', models.BooleanField(default=False)),
                ('check_by_time', models.BooleanField(default=False)),
                ('responsible_for_doing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('done_status', models.BooleanField(default=False)),
                ('description', models.TextField(null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_category', to='ProjectManager.categoryproject')),
                ('check_list', models.ManyToManyField(to='ProjectManager.checklist')),
                ('file', models.ManyToManyField(to='ProjectManager.file')),
                ('task_label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.tasklabel')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('category_project', models.ManyToManyField(to='ProjectManager.categoryproject')),
                ('members', models.ManyToManyField(related_name='project_members', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_project', to=settings.AUTH_USER_MODEL)),
                ('chat', models.ManyToManyField(blank=True, to='ProjectManager.projectchat')),
                ('task', models.ManyToManyField(blank=True, to='ProjectManager.task')),
            ],
        ),
    ]
