# Generated by Django 5.1 on 2024-11-13 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0002_remove_project_owner'),
        ('core', '0005_mainfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mainfile'),
        ),
        migrations.AddField(
            model_name='projectchat',
            name='main_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mainfile'),
        ),
    ]
