# Generated by Django 5.1 on 2024-11-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0003_project_avatar_projectchat_main_file'),
        ('core', '0005_mainfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='file',
        ),
        migrations.AddField(
            model_name='task',
            name='main_file',
            field=models.ManyToManyField(to='core.mainfile'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
