# Generated by Django 5.1 on 2024-11-14 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0004_remove_task_file_task_main_file_delete_file'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mainfile'),
        ),
        migrations.AlterField(
            model_name='projectchat',
            name='main_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mainfile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_category', to='ProjectManager.categoryproject'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectManager.tasklabel'),
        ),
    ]
