# Generated by Django 5.1 on 2024-11-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0005_alter_project_avatar_alter_projectchat_main_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProjectManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='categoryproject',
            name='color_code',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
