# Generated by Django 5.1 on 2024-11-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0006_categoryprojectmanager_categoryproject_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproject',
            name='order',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
