# Generated by Django 5.1 on 2024-11-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0007_categoryproject_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryProjectManager',
        ),
    ]
