# Generated by Django 5.1 on 2024-11-18 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0008_delete_categoryprojectmanager'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectchat',
            name='voice_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_chat_voice', to='core.mainfile'),
        ),
        migrations.AlterField(
            model_name='projectchat',
            name='main_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_chat_file', to='core.mainfile'),
        ),
    ]
