# Generated by Django 5.1 on 2024-11-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0009_projectchat_voice_file_alter_projectchat_main_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
