# Generated by Django 5.1 on 2024-11-23 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0010_alter_checklist_title_alter_task_title'),
        ('WorkSpaceManager', '0010_remove_workspace_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='WorkSpaceManager.workspace'),
        ),
    ]
