# Generated by Django 5.1 on 2024-11-24 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0011_project_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='check_list',
        ),
        migrations.AddField(
            model_name='checklist',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_list', to='ProjectManager.task'),
        ),
    ]
