# Generated by Django 5.1 on 2024-11-24 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0012_remove_task_check_list_checklist_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category_project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='task',
        ),
        migrations.AddField(
            model_name='categoryproject',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_project', to='ProjectManager.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='ProjectManager.project'),
        ),
    ]
