# Generated by Django 5.1 on 2024-12-07 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0014_remove_task_task_label_checklist_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklabel',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.project'),
        ),
    ]
