# Generated by Django 5.1 on 2024-12-08 10:06

import django.db.models.deletion
import django.db.models.fields.related
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0015_tasklabel_project'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file', models.ManyToManyField(null=True, to='core.mainfile')),
                ('replay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.taskreport')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.fields.related.ForeignKey, to='ProjectManager.task')),
            ],
        ),
    ]
