# Generated by Django 5.1 on 2024-12-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0016_taskreport'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreport',
            name='file',
            field=models.ManyToManyField(to='core.mainfile'),
        ),
    ]
