# Generated by Django 5.1 on 2024-12-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0017_alter_taskreport_file'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreport',
            name='file',
            field=models.ManyToManyField(blank=True, to='core.mainfile'),
        ),
    ]
