# Generated by Django 5.1 on 2025-01-26 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0018_alter_taskreport_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproject',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_project', to='ProjectManager.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='ProjectManager.project'),
        ),
    ]
