# Generated by Django 5.1 on 2025-02-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0020_project_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklabel',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
