# Generated by Django 5.1 on 2025-02-06 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0021_tasklabel_order'),
        ('WorkSpaceManager', '0026_workspacemember_is_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_departments', to='WorkSpaceManager.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_department', to='ProjectManager.projectdepartment'),
        ),
    ]
