# Generated by Django 5.1 on 2025-02-11 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0023_projectdepartment_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectchat',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_projects', to='ProjectManager.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='chat',
            field=models.ManyToManyField(blank=True, related_name='projects_chats', to='ProjectManager.projectchat'),
        ),
    ]
