# Generated by Django 5.1 on 2025-02-19 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0024_projectchat_project_alter_project_chat'),
        ('WorkSpaceManager', '0030_alter_workspace_options_workspace_created_at_and_more'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproject',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='checklist',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectchat',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectdepartment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='taskreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='categoryproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='categoryproject',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='categoryproject',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='categoryproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='projectchat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='projectchat',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='projectchat',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='projectchat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='projectdepartment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='projectdepartment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='projectdepartment',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='projectdepartment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='taskreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='taskreport',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='taskreport',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='taskreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='categoryproject',
            index=models.Index(fields=['is_deleted'], name='ProjectMana_is_dele_eda850_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryproject',
            index=models.Index(fields=['deleted_at'], name='ProjectMana_deleted_c3c4a6_idx'),
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['is_deleted'], name='ProjectMana_is_dele_35c593_idx'),
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['deleted_at'], name='ProjectMana_deleted_5dc1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_deleted'], name='ProjectMana_is_dele_1a9367_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['deleted_at'], name='ProjectMana_deleted_c344bd_idx'),
        ),
        migrations.AddIndex(
            model_name='projectchat',
            index=models.Index(fields=['is_deleted'], name='ProjectMana_is_dele_011d01_idx'),
        ),
        migrations.AddIndex(
            model_name='projectchat',
            index=models.Index(fields=['deleted_at'], name='ProjectMana_deleted_aef7bb_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdepartment',
            index=models.Index(fields=['is_deleted'], name='ProjectMana_is_dele_156536_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdepartment',
            index=models.Index(fields=['deleted_at'], name='ProjectMana_deleted_ab5576_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_deleted'], name='ProjectMana_is_dele_3a3d06_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deleted_at'], name='ProjectMana_deleted_37c6d1_idx'),
        ),
        migrations.AddIndex(
            model_name='taskreport',
            index=models.Index(fields=['is_deleted'], name='ProjectMana_is_dele_5d11c4_idx'),
        ),
        migrations.AddIndex(
            model_name='taskreport',
            index=models.Index(fields=['deleted_at'], name='ProjectMana_deleted_261896_idx'),
        ),
    ]
