# Generated by Django 5.1 on 2025-02-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0025_alter_categoryproject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklabel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='tasklabel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='tasklabel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='tasklabel',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='tasklabel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='tasklabel',
            index=models.Index(fields=['is_deleted'], name='ProjectMana_is_dele_135d53_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklabel',
            index=models.Index(fields=['deleted_at'], name='ProjectMana_deleted_537e37_idx'),
        ),
    ]
