# Generated by Django 5.1.6 on 2025-03-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0027_checklist_difficulty'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='file',
            field=models.ManyToManyField(blank=True, to='core.mainfile'),
        ),
    ]
