# Generated by Django 5.1.6 on 2025-03-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0028_checklist_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='date_time_to_end_main',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='date_time_to_start_main',
            field=models.DateTimeField(null=True),
        ),
    ]
