# Generated by Django 5.1 on 2025-05-04 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0030_projectmessage'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmessage',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='projectmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'TEXT'), ('notification', 'NOTIFICATION')], default='text', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='projectmessage',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
