# Generated by Django 5.1 on 2025-05-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0031_projectmessage_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmessage',
            name='message_type',
            field=models.CharField(blank=True, choices=[('text', 'TEXT'), ('notification', 'NOTIFICATION')], default='text', max_length=15, null=True),
        ),
    ]
