# Generated by Django 5.1 on 2025-05-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0032_alter_projectmessage_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_list_type', models.CharField(choices=[('no_timing', 'NoTiming'), ('based_on_timing', 'BasedOnTiming'), ('based_on_difficulty', 'BasedOnDifficulty')], default='no_timing', max_length=25, null=True)),
            ],
        ),
    ]
