# Generated by Django 5.1 on 2025-05-10 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0034_timer_delete_testtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckListTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('elapsed_time', models.DurationField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='stopped', max_length=10)),
                ('is_done', models.BooleanField(default=False)),
                ('check_list', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timer', to='ProjectManager.checklist')),
            ],
        ),
        migrations.DeleteModel(
            name='Timer',
        ),
    ]
