# Generated by Django 5.1 on 2025-05-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0035_checklisttimer_delete_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
