# Generated by Django 5.1 on 2025-05-11 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0036_alter_task_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='check_list_type',
            field=models.CharField(choices=[('no_schedule', 'NoSchedule'), ('with_schedule', 'WithSchedule'), ('based_on_weight', 'BasedOnWeight')], default='no_schedule', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='checklisttimer',
            name='elapsed_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
