# Generated by Django 5.1 on 2025-05-11 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0037_checklist_check_list_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklisttimer',
            name='check_list',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timer', to='ProjectManager.checklist'),
        ),
    ]
