# Generated by Django 5.1 on 2025-05-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0038_alter_checklisttimer_check_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklisttimer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='checklisttimer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='checklisttimer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='checklisttimer',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='checklisttimer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='check_list_type',
            field=models.CharField(blank=True, choices=[('no_schedule', 'NoSchedule'), ('with_schedule', 'WithSchedule'), ('based_on_weight', 'BasedOnWeight')], default='no_schedule', max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='checklisttimer',
            index=models.Index(fields=['is_deleted'], name='ProjectMana_is_dele_a55fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='checklisttimer',
            index=models.Index(fields=['deleted_at'], name='ProjectMana_deleted_3e7f0b_idx'),
        ),
    ]
