# Generated by Django 4.2.21 on 2025-05-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0040_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
