# Generated by Django 4.2.21 on 2025-05-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0041_alter_checklist_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='is_neon',
            field=models.BooleanField(default=False),
        ),
    ]
