# Generated by Django 5.1 on 2024-11-13 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailManager', '0001_initial'),
        ('core', '0005_mainfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='main_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mainfile'),
        ),
    ]
