# Generated by Django 5.1 on 2025-01-11 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailManager', '0004_messagelabel_order'),
        ('WorkSpaceManager', '0020_workspace_activated'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, null=True)),
                ('color_code', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='conversation_label',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='createor',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='message',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='reciver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='main_file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_reciver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_sender',
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('signature_status', models.BooleanField(default=False)),
                ('description', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mail_code', models.CharField(max_length=200, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('files', models.ManyToManyField(to='core.mainfile')),
                ('mail_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_image_file', to='core.mainfile')),
                ('members', models.ManyToManyField(related_name='mail_member', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkSpaceManager.workspace')),
                ('label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MailManager.maillabel')),
            ],
        ),
        migrations.CreateModel(
            name='SignatureMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MailManager.mail')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('signature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mainfile')),
            ],
        ),
        migrations.DeleteModel(
            name='MessageLabel',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
