# Generated by Django 5.1 on 2025-01-11 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MailManager', '0005_maillabel_remove_conversation_conversation_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='description',
            new_name='mail_text',
        ),
    ]
