# Generated by Django 5.1 on 2025-01-11 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailManager', '0006_rename_description_mail_mail_text'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='files',
            field=models.ManyToManyField(blank=True, to='core.mainfile'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mail_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_image_file', to='core.mainfile'),
        ),
    ]
