# Generated by Django 5.1 on 2025-01-11 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailManager', '0007_alter_mail_files_alter_mail_mail_image'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturemail',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='signaturemail',
            name='signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='core.mainfile'),
        ),
    ]
