# Generated by Django 5.1 on 2025-01-11 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailManager', '0008_signaturemail_order_alter_signaturemail_signature'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturemail',
            name='mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='MailManager.mail'),
        ),
        migrations.AlterField(
            model_name='signaturemail',
            name='signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mainfile'),
        ),
    ]
