# Generated by Django 5.1 on 2025-01-11 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailManager', '0009_alter_signaturemail_mail_and_more'),
        ('WorkSpaceManager', '0020_workspace_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='maillabel',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkSpaceManager.workspace'),
        ),
    ]
