# Generated by Django 5.1 on 2025-01-14 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailManager', '0010_maillabel_workspace'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('files', models.ManyToManyField(to='core.mainfile')),
                ('mail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_reports', to='MailManager.mail')),
            ],
        ),
    ]
