# Generated by Django 5.1 on 2025-01-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailManager', '0012_mailreport_creator'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailreport',
            name='files',
            field=models.ManyToManyField(blank=True, to='core.mainfile'),
        ),
    ]
