# Generated by Django 5.1 on 2025-01-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailManager', '0013_alter_mailreport_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturemail',
            name='sign_status',
            field=models.BooleanField(default=False),
        ),
    ]
