# Generated by Django 5.1 on 2025-01-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailManager', '0014_signaturemail_sign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='mail_code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
