# Generated by Django 5.1 on 2025-01-18 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailManager', '0016_mailstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailstatus',
            name='mail',
        ),
        migrations.AddField(
            model_name='mail',
            name='status_mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MailManager.mailstatus'),
        ),
    ]
