# Generated by Django 5.1 on 2025-01-18 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailManager', '0017_remove_mailstatus_mail_mail_status_mail'),
        ('WorkSpaceManager', '0020_workspace_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailstatus',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkSpaceManager.workspace'),
        ),
    ]
