# Generated by Django 5.1 on 2025-01-19 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailManager', '0019_favoritemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritemail',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='favoritemail',
            name='object_id',
        ),
        migrations.AddField(
            model_name='favoritemail',
            name='mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MailManager.mail'),
        ),
    ]
