# Generated by Django 5.1 on 2025-01-20 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailManager', '0021_mailaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailaction',
            name='color_code',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mailaction',
            name='user_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_actionZ', to=settings.AUTH_USER_MODEL),
        ),
    ]
