# Generated by Django 5.1 on 2025-02-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MailManager', '0024_mailstatus_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailstatus',
            name='name',
        ),
    ]
