# Generated by Django 5.1.6 on 2025-03-11 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailManager', '0025_remove_mailstatus_name'),
        ('WorkSpaceManager', '0042_workspacepermission_is_active'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('recipient_type', models.CharField(choices=[('sign', 'SIGN'), ('cc', 'CC'), ('vcc', 'VCC')], default='cc', max_length=10)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='categorydraft',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='draft',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='favoritemail',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='mail',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='mailaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='maillabel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='mailreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='mailstatus',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='signaturemail',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='categorydraft',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='categorydraft',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='categorydraft',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='categorydraft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='draft',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='draft',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='draft',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='draft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='favoritemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='favoritemail',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='favoritemail',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='favoritemail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='mail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='mail',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='mail',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='mail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='mailaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='mailaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='mailaction',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='mailaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='maillabel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='maillabel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='maillabel',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='maillabel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='mailreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='mailreport',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='mailreport',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='mailreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='mailstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='mailstatus',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='mailstatus',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='mailstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='signaturemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='signaturemail',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='signaturemail',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='signaturemail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='categorydraft',
            index=models.Index(fields=['is_deleted'], name='MailManager_is_dele_ac31f7_idx'),
        ),
        migrations.AddIndex(
            model_name='categorydraft',
            index=models.Index(fields=['deleted_at'], name='MailManager_deleted_17ea5c_idx'),
        ),
        migrations.AddIndex(
            model_name='draft',
            index=models.Index(fields=['is_deleted'], name='MailManager_is_dele_cd96f0_idx'),
        ),
        migrations.AddIndex(
            model_name='draft',
            index=models.Index(fields=['deleted_at'], name='MailManager_deleted_a388af_idx'),
        ),
        migrations.AddIndex(
            model_name='favoritemail',
            index=models.Index(fields=['is_deleted'], name='MailManager_is_dele_d0c958_idx'),
        ),
        migrations.AddIndex(
            model_name='favoritemail',
            index=models.Index(fields=['deleted_at'], name='MailManager_deleted_29b860_idx'),
        ),
        migrations.AddIndex(
            model_name='mail',
            index=models.Index(fields=['is_deleted'], name='MailManager_is_dele_ea2ece_idx'),
        ),
        migrations.AddIndex(
            model_name='mail',
            index=models.Index(fields=['deleted_at'], name='MailManager_deleted_7be07e_idx'),
        ),
        migrations.AddIndex(
            model_name='mailaction',
            index=models.Index(fields=['is_deleted'], name='MailManager_is_dele_a78252_idx'),
        ),
        migrations.AddIndex(
            model_name='mailaction',
            index=models.Index(fields=['deleted_at'], name='MailManager_deleted_663477_idx'),
        ),
        migrations.AddIndex(
            model_name='maillabel',
            index=models.Index(fields=['is_deleted'], name='MailManager_is_dele_e089b3_idx'),
        ),
        migrations.AddIndex(
            model_name='maillabel',
            index=models.Index(fields=['deleted_at'], name='MailManager_deleted_49815f_idx'),
        ),
        migrations.AddIndex(
            model_name='mailreport',
            index=models.Index(fields=['is_deleted'], name='MailManager_is_dele_b2c004_idx'),
        ),
        migrations.AddIndex(
            model_name='mailreport',
            index=models.Index(fields=['deleted_at'], name='MailManager_deleted_57bd13_idx'),
        ),
        migrations.AddIndex(
            model_name='mailstatus',
            index=models.Index(fields=['is_deleted'], name='MailManager_is_dele_ca368a_idx'),
        ),
        migrations.AddIndex(
            model_name='mailstatus',
            index=models.Index(fields=['deleted_at'], name='MailManager_deleted_d6d21b_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturemail',
            index=models.Index(fields=['is_deleted'], name='MailManager_is_dele_881362_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturemail',
            index=models.Index(fields=['deleted_at'], name='MailManager_deleted_940310_idx'),
        ),
        migrations.AddField(
            model_name='mailrecipient',
            name='mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='MailManager.mail'),
        ),
        migrations.AddField(
            model_name='mailrecipient',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mailrecipient',
            index=models.Index(fields=['is_deleted'], name='MailManager_is_dele_d10e51_idx'),
        ),
        migrations.AddIndex(
            model_name='mailrecipient',
            index=models.Index(fields=['deleted_at'], name='MailManager_deleted_c0f8fc_idx'),
        ),
    ]
