# Generated by Django 5.1.6 on 2025-03-11 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailManager', '0026_mailrecipient_alter_categorydraft_options_and_more'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailrecipient',
            name='signature_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mainfile'),
        ),
        migrations.AddField(
            model_name='mailrecipient',
            name='signature_status',
            field=models.BooleanField(default=False),
        ),
    ]
