# Generated by Django 5.1.6 on 2025-03-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailManager', '0027_mailrecipient_signature_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailreport',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
