# Generated by Django 5.1.6 on 2025-02-22 21:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceChat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='members',
            field=models.ManyToManyField(related_name='group_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
