# Generated by Django 5.1.6 on 2025-03-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSpaceChat', '0002_alter_groupmessage_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
