# Generated by Django 5.1 on 2024-11-09 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=27)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, null=True)),
                ('color_code', models.CharField(max_length=55, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_status', models.CharField(choices=[('در انتظار', 'در انتظار'), ('بسته شده', 'بسته شده'), ('تایید شده', 'تایید شده')], max_length=30, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('anon_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SupportManager.anoncustomer')),
                ('category_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SupportManager.categoryroom')),
                ('user_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='images/roommessages/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SupportManager.roommessage')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SupportManager.room')),
            ],
        ),
    ]
