# Generated by Django 5.1 on 2024-11-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessage',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
