# Generated by Django 5.1 on 2024-11-09 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportManager', '0002_roommessage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommessage',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SupportManager.roommessage'),
        ),
    ]
