# Generated by Django 5.1 on 2024-11-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportManager', '0003_alter_roommessage_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='anoncustomer',
            name='refrence_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
