# Generated by Django 5.1 on 2024-11-09 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportManager', '0004_anoncustomer_refrence_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessage',
            name='anonymous_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SupportManager.anoncustomer'),
        ),
        migrations.AddField(
            model_name='roommessage',
            name='message_type',
            field=models.CharField(choices=[('ناشناس', 'ناشناس'), ('اپراتور', 'اپراتور')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='roommessage',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='anoncustomer',
            name='phone_number',
            field=models.CharField(max_length=27, null=True),
        ),
    ]
