# Generated by Django 5.1 on 2024-11-09 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportManager', '0005_roommessage_anonymous_user_roommessage_message_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommessage',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='SupportManager.room'),
        ),
    ]
