# Generated by Django 5.1 on 2024-11-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportManager', '0007_alter_roommessage_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessage',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
    ]
