# Generated by Django 5.1 on 2024-12-07 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportManager', '0008_roommessage_read_status'),
        ('WorkSpaceManager', '0017_workspace_avatar_workspacemember_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryroom',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkSpaceManager.workspace'),
        ),
        migrations.AddField(
            model_name='room',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkSpaceManager.workspace'),
        ),
    ]
