# Generated by Django 5.1 on 2024-12-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportManager', '0010_remove_room_category_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anoncustomer',
            name='phone_number',
            field=models.CharField(max_length=27, null=True),
        ),
    ]
