# Generated by Django 5.1 on 2024-12-24 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportManager', '0012_remove_department_workspace_and_more'),
        ('WorkSpaceManager', '0018_workspacemember_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SupportManager.anoncustomer')),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkSpaceManager.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SupportManager.grouproom'),
        ),
    ]
