# Generated by Django 5.1 on 2024-12-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportManager', '0013_grouproom_room_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouproom',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
