# Generated by Django 5.1 on 2024-12-25 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportManager', '0014_grouproom_status'),
        ('WorkSpaceManager', '0018_workspacemember_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkSpaceManager.workspace'),
        ),
    ]
