# Generated by Django 5.1 on 2024-12-28 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportManager', '0015_department_workspace'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_message', to='core.mainfile'),
        ),
        migrations.AddField(
            model_name='roommessage',
            name='voice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_message', to='core.mainfile'),
        ),
    ]
