# Generated by Django 5.1 on 2024-10-28 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomerFinance', '__first__'),
        ('core', '0002_city_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('status', 'status'), ('invoice', 'invoice'), ('refrral', 'refrral')], max_length=50, null=True)),
                ('object_id', models.IntegerField(default=0)),
                ('user_author', models.IntegerField(default=0)),
                ('user_reciver', models.IntegerField(default=0)),
                ('before_status', models.CharField(max_length=40, null=True)),
                ('current_status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='bermoda/report_files')),
                ('report_type', models.BooleanField(default=False)),
                ('action_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CrmCore.actiondata')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_to_remember', models.CharField(max_length=30, null=True)),
                ('time_to_remember', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(null=True)),
                ('position', models.CharField(max_length=40, null=True)),
                ('call_number', models.CharField(max_length=40, null=True)),
                ('address', models.TextField(null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('personal_type', models.CharField(choices=[('حقیقی', 'حقیقی'), ('حقوقی', 'حقوقی')], max_length=9, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CrmCore.category')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city')),
                ('invoice', models.ManyToManyField(blank=True, related_name='customer_invoice', to='CustomerFinance.invoice')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state')),
                ('label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CrmCore.label')),
                ('report', models.ManyToManyField(blank=True, to='CrmCore.report')),
            ],
        ),
    ]
