# Generated by Django 5.1 on 2024-10-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0003_alter_customeruser_category_alter_customeruser_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
