# Generated by Django 5.1 on 2024-11-13 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0005_alter_report_file'),
        ('core', '0005_mainfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mainfile'),
        ),
    ]
