# Generated by Django 5.1 on 2024-11-13 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0006_alter_report_file'),
        ('core', '0005_mainfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='main_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mainfile'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bermoda/report_files'),
        ),
    ]
