# Generated by Django 5.1 on 2024-11-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0008_remove_report_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='main_file',
        ),
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bermoda/report_files'),
        ),
    ]
