# Generated by Django 5.1 on 2024-11-13 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0009_remove_report_main_file_report_file'),
        ('core', '0005_mainfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='main_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mainfile'),
        ),
    ]
