# Generated by Django 5.1 on 2024-11-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0010_report_main_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='file',
        ),
    ]
