# Generated by Django 5.1 on 2024-11-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0013_customeruser_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='representative_name',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
