# Generated by Django 5.1 on 2024-11-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0018_groupcrm_customeruser_group_crm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupcrm',
            old_name='user_account',
            new_name='members',
        ),
    ]
