# Generated by Django 5.1 on 2024-11-24 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0019_rename_user_account_groupcrm_members'),
        ('WorkSpaceManager', '0011_remove_workspace_member_workspacemember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='possibility_of_sale',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='groupcrm',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_crm', to='WorkSpaceManager.workspace'),
        ),
        migrations.AlterField(
            model_name='groupcrm',
            name='members',
            field=models.ManyToManyField(related_name='group_crm_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
