# Generated by Django 5.1 on 2024-11-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0020_customeruser_email_customeruser_possibility_of_sale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeruser',
            old_name='call_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='customeruser',
            old_name='first_name',
            new_name='phone_number_static',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='date_to_remember',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='position',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='representative_name',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='time_to_remember',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='agent_email_or_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='agent_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='agent_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='agent_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='economic_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='fax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='fullname_or_company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='legal_information',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='manager_national_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='manager_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='date_to_remember',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='time_to_remember',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
