# Generated by Django 5.1 on 2024-11-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0021_rename_call_number_customeruser_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='possibility_of_sale',
        ),
        migrations.AddField(
            model_name='report',
            name='possibility_of_sale',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
