# Generated by Django 5.1 on 2024-11-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0022_remove_customeruser_possibility_of_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
