# Generated by Django 5.1 on 2024-11-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0024_report_invoice_id_report_label_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='economic_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='fax',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='manager_national_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='manager_phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
