# Generated by Django 5.1 on 2024-11-30 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0025_alter_customeruser_economic_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_label', to='CrmCore.label'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
