# Generated by Django 5.1 on 2024-12-07 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0026_alter_customeruser_label_alter_customeruser_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='workspace',
        ),
        migrations.AddField(
            model_name='label',
            name='group_crm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_customer', to='CrmCore.groupcrm'),
        ),
    ]
