# Generated by Django 5.1 on 2024-12-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0027_remove_label_workspace_label_group_crm'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='agent_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
