# Generated by Django 5.1 on 2024-12-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0028_customeruser_agent_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='payment_date_to_remember',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='payment_time_to_remember',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
