# Generated by Django 5.1 on 2024-12-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0029_report_payment_date_to_remember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='report',
            field=models.ManyToManyField(blank=True, related_name='customer_user', to='CrmCore.report'),
        ),
    ]
