# Generated by Django 5.1 on 2024-12-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0030_alter_customeruser_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='notif_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='notif_remember',
            field=models.BooleanField(default=False),
        ),
    ]
