# Generated by Django 5.1 on 2025-01-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0031_report_notif_payment_report_notif_remember'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
