# Generated by Django 5.1 on 2025-02-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0032_label_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='date_time_to_remember',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='possibility_of_sale',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='phone_number_static',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
