# Generated by Django 5.1 on 2025-02-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0035_remove_label_order_groupcrm_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='conection_type',
            field=models.CharField(choices=[('phone', 'PHONE'), ('email', 'EMAIL')], default='phone', max_length=30),
        ),
    ]
