# Generated by Django 5.1 on 2025-02-13 10:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0038_alter_customeruser_avatar'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('field_type', models.CharField(choices=[('fullname', 'FULLNAME'), ('phone_number', 'PHONE_NUMBER'), ('email', 'EMAIL'), ('telegram_id', 'TELEGRAM_id'), ('instagram_id', 'INSTAGRAM_ID'), ('website', 'WEBSITE')], max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('description', models.TextField(null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('group_crm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='CrmCore.groupcrm')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mainfile')),
                ('fields_accepted', models.ManyToManyField(to='CrmCore.campaignfield')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_forms', to='CrmCore.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaignfield',
            name='campaign_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_fields', to='CrmCore.campaignform'),
        ),
    ]
