# Generated by Django 5.1 on 2025-02-13 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0040_campaign_created_campaign_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignfield',
            name='campaign_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_fields', to='CrmCore.campaignform'),
        ),
    ]
