# Generated by Django 5.1 on 2025-02-16 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0041_alter_campaignfield_campaign_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='fields_accepted',
        ),
        migrations.RemoveField(
            model_name='campaignfield',
            name='campaign_form',
        ),
        migrations.RemoveField(
            model_name='campaignfield',
            name='text',
        ),
        migrations.AddField(
            model_name='campaignfield',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='CrmCore.campaign'),
        ),
        migrations.AddField(
            model_name='campaignfield',
            name='title',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='campaignfield',
            name='field_type',
            field=models.CharField(choices=[('fullname', 'FULLNAME'), ('phone_number', 'PHONE_NUMBER'), ('text', 'TEXT'), ('number', 'NUMBER'), ('email', 'EMAIL'), ('link', 'LINK')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='campaignform',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='CrmCore.campaign'),
        ),
        migrations.CreateModel(
            name='CampaignFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, null=True)),
                ('text', models.TextField(null=True)),
                ('campaign_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_data', to='CrmCore.campaignform')),
            ],
        ),
    ]
