# Generated by Django 5.1 on 2025-02-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0042_remove_campaign_fields_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignfield',
            name='field_type',
            field=models.CharField(choices=[('phone_number', 'PHONE_NUMBER'), ('text', 'TEXT'), ('number', 'NUMBER'), ('email', 'EMAIL'), ('link', 'LINK')], max_length=60, null=True),
        ),
    ]
