# Generated by Django 5.1 on 2025-02-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0044_campaignform_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignformdata',
            name='field_type',
            field=models.CharField(choices=[('phone_number', 'PHONE_NUMBER'), ('text', 'TEXT'), ('number', 'NUMBER'), ('email', 'EMAIL'), ('link', 'LINK')], max_length=60, null=True),
        ),
    ]
