# Generated by Django 5.1 on 2025-02-17 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0045_campaignformdata_field_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpExist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(null=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CrmCore.campaign')),
            ],
        ),
    ]
