# Generated by Django 5.1 on 2025-02-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0046_ipexist'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAshol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(null=True)),
            ],
        ),
    ]
