# Generated by Django 5.1 on 2025-02-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0047_ipashol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IpAshol',
        ),
    ]
