# Generated by Django 5.1 on 2025-02-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0048_delete_ipashol'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAshol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('ip', models.GenericIPAddressField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_deleted'], name='CrmCore_ipa_is_dele_101795_idx'), models.Index(fields=['deleted_at'], name='CrmCore_ipa_deleted_58423c_idx')],
            },
        ),
    ]
