# Generated by Django 5.1 on 2025-02-19 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0050_alter_ipashol_created_at_alter_ipashol_updated_at'),
        ('CustomerFinance', '0005_alter_information_email'),
        ('WorkSpaceManager', '0031_alter_industrialactivity_options_alter_link_options_and_more'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actiondata',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='campaignfield',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='campaignform',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='campaignformdata',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='crmdepartment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='customeruser',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='groupcrm',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ipexist',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='actiondata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='actiondata',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='actiondata',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='actiondata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='campaignfield',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='campaignfield',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='campaignfield',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='campaignfield',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='campaignform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='campaignform',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='campaignform',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='campaignform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='campaignformdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='campaignformdata',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='campaignformdata',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='campaignformdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='crmdepartment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='crmdepartment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='crmdepartment',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='crmdepartment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='groupcrm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='groupcrm',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='groupcrm',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='groupcrm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='ipexist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='ipexist',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='ipexist',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='ipexist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='label',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='label',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='label',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='label',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='report',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='report',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='actiondata',
            index=models.Index(fields=['is_deleted'], name='CrmCore_act_is_dele_d8c367_idx'),
        ),
        migrations.AddIndex(
            model_name='actiondata',
            index=models.Index(fields=['deleted_at'], name='CrmCore_act_deleted_198cc0_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['is_deleted'], name='CrmCore_cam_is_dele_e07dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['deleted_at'], name='CrmCore_cam_deleted_895a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignfield',
            index=models.Index(fields=['is_deleted'], name='CrmCore_cam_is_dele_9f8a27_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignfield',
            index=models.Index(fields=['deleted_at'], name='CrmCore_cam_deleted_6d8c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignform',
            index=models.Index(fields=['is_deleted'], name='CrmCore_cam_is_dele_cf4575_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignform',
            index=models.Index(fields=['deleted_at'], name='CrmCore_cam_deleted_14079c_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignformdata',
            index=models.Index(fields=['is_deleted'], name='CrmCore_cam_is_dele_1f8efc_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignformdata',
            index=models.Index(fields=['deleted_at'], name='CrmCore_cam_deleted_b8666c_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_deleted'], name='CrmCore_cat_is_dele_1097b3_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['deleted_at'], name='CrmCore_cat_deleted_6386d6_idx'),
        ),
        migrations.AddIndex(
            model_name='crmdepartment',
            index=models.Index(fields=['is_deleted'], name='CrmCore_crm_is_dele_6115e3_idx'),
        ),
        migrations.AddIndex(
            model_name='crmdepartment',
            index=models.Index(fields=['deleted_at'], name='CrmCore_crm_deleted_faba92_idx'),
        ),
        migrations.AddIndex(
            model_name='customeruser',
            index=models.Index(fields=['is_deleted'], name='CrmCore_cus_is_dele_475f24_idx'),
        ),
        migrations.AddIndex(
            model_name='customeruser',
            index=models.Index(fields=['deleted_at'], name='CrmCore_cus_deleted_c3e8a2_idx'),
        ),
        migrations.AddIndex(
            model_name='groupcrm',
            index=models.Index(fields=['is_deleted'], name='CrmCore_gro_is_dele_ce1fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='groupcrm',
            index=models.Index(fields=['deleted_at'], name='CrmCore_gro_deleted_c6275d_idx'),
        ),
        migrations.AddIndex(
            model_name='ipexist',
            index=models.Index(fields=['is_deleted'], name='CrmCore_ipe_is_dele_23c58e_idx'),
        ),
        migrations.AddIndex(
            model_name='ipexist',
            index=models.Index(fields=['deleted_at'], name='CrmCore_ipe_deleted_a6ef45_idx'),
        ),
        migrations.AddIndex(
            model_name='label',
            index=models.Index(fields=['is_deleted'], name='CrmCore_lab_is_dele_4267bb_idx'),
        ),
        migrations.AddIndex(
            model_name='label',
            index=models.Index(fields=['deleted_at'], name='CrmCore_lab_deleted_36f104_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['is_deleted'], name='CrmCore_rep_is_dele_c867cb_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['deleted_at'], name='CrmCore_rep_deleted_5575cc_idx'),
        ),
    ]
