# Generated by Django 5.1 on 2025-02-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0051_alter_actiondata_options_alter_campaign_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
