# Generated by Django 5.1 on 2025-02-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0052_customeruser_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
