# Generated by Django 5.1.6 on 2025-03-04 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0053_alter_customeruser_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='groupcrm',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='LabelStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_steps', to='CrmCore.label')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=30, null=True)),
                ('step', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('label_step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='CrmCore.labelstep')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_step', to='CrmCore.customeruser')),
                ('label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CrmCore.label')),
                ('step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CrmCore.step')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='labelstep',
            index=models.Index(fields=['is_deleted'], name='CrmCore_lab_is_dele_2674ab_idx'),
        ),
        migrations.AddIndex(
            model_name='labelstep',
            index=models.Index(fields=['deleted_at'], name='CrmCore_lab_deleted_1a4fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='step',
            index=models.Index(fields=['is_deleted'], name='CrmCore_ste_is_dele_2b964c_idx'),
        ),
        migrations.AddIndex(
            model_name='step',
            index=models.Index(fields=['deleted_at'], name='CrmCore_ste_deleted_df69a7_idx'),
        ),
        migrations.AddIndex(
            model_name='customerstep',
            index=models.Index(fields=['is_deleted'], name='CrmCore_cus_is_dele_8cfc71_idx'),
        ),
        migrations.AddIndex(
            model_name='customerstep',
            index=models.Index(fields=['deleted_at'], name='CrmCore_cus_deleted_558382_idx'),
        ),
    ]
