# Generated by Django 5.1.6 on 2025-03-04 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0054_customeruser_created_groupcrm_created_labelstep_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelstep',
            name='label',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_step', to='CrmCore.label'),
        ),
        migrations.AlterField(
            model_name='step',
            name='step',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
