# Generated by Django 5.1.6 on 2025-03-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0055_alter_labelstep_label_alter_step_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='is_followed',
            field=models.BooleanField(default=False),
        ),
    ]
