# Generated by Django 5.1.6 on 2025-03-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0056_customeruser_is_followed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='main_date_time_to_remember',
            field=models.DateTimeField(null=True),
        ),
    ]
