# Generated by Django 5.1.6 on 2025-03-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0057_customeruser_main_date_time_to_remember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='invoice',
        ),
    ]
