# Generated by Django 5.1.6 on 2025-03-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0058_remove_customeruser_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
