# Generated by Django 5.1.6 on 2025-03-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0059_label_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
