# Generated by Django 5.1.6 on 2025-03-17 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0060_customeruser_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('exel_file', models.FileField(null=True, upload_to='customer_exels/')),
                ('group_crm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CrmCore.groupcrm')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('phone_number', models.CharField(max_length=14, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('static_phone_number', models.CharField(max_length=18, null=True)),
                ('address', models.TextField(null=True)),
                ('email', models.CharField(max_length=60, null=True)),
                ('fullname_or_company_name', models.CharField(max_length=40, null=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CrmCore.customerdocument')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='customerdocument',
            index=models.Index(fields=['is_deleted'], name='CrmCore_cus_is_dele_319b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='customerdocument',
            index=models.Index(fields=['deleted_at'], name='CrmCore_cus_deleted_4a3a53_idx'),
        ),
        migrations.AddIndex(
            model_name='customerbank',
            index=models.Index(fields=['is_deleted'], name='CrmCore_cus_is_dele_9de33e_idx'),
        ),
        migrations.AddIndex(
            model_name='customerbank',
            index=models.Index(fields=['deleted_at'], name='CrmCore_cus_deleted_b72996_idx'),
        ),
    ]
