# Generated by Django 5.1.6 on 2025-03-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0062_alter_customerdocument_exel_file'),
        ('core', '0006_mainfile_created_mainfile_workspace_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbank',
            name='is_local',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerbank',
            name='main_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city'),
        ),
        migrations.AddField(
            model_name='customerbank',
            name='main_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state'),
        ),
        migrations.AlterField(
            model_name='customerbank',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerbank',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
