# Generated by Django 5.1.6 on 2025-04-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0063_customerbank_is_local_customerbank_main_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='customer_status',
            field=models.CharField(choices=[('DONT_FOLLOWED', 'dont_followed'), ('FOLLOW_IN_ANOTHER_TIME', 'follow_in_another_time'), ('SUCCESSFUL_SELL', 'successful_sell')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='last_selling_invoice_id',
            field=models.IntegerField(default=0),
        ),
    ]
