# Generated by Django 5.1.6 on 2025-04-08 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0065_alter_customeruser_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='group_crm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='CrmCore.groupcrm'),
        ),
    ]
