# Generated by Django 5.1 on 2025-04-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0067_customeruser_gender_customeruser_industrial_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
