# Generated by Django 5.1 on 2025-04-30 10:24

import django.db.models.deletion
import django.db.models.fields.related
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0068_alter_customeruser_fax'),
        ('core', '0012_reminder_remind_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCrmMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this record is soft deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when this record was soft deleted', null=True, verbose_name='Deleted At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file', models.ManyToManyField(blank=True, to='core.mainfile')),
                ('group_crm', models.ForeignKey(null=True, on_delete=django.db.models.fields.related.ForeignKey, related_name='messages', to='CrmCore.groupcrm')),
                ('replay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CrmCore.groupcrmmessage')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_deleted'], name='CrmCore_gro_is_dele_fcc28a_idx'), models.Index(fields=['deleted_at'], name='CrmCore_gro_deleted_f7632e_idx')],
            },
        ),
    ]
