# Generated by Django 5.1 on 2025-05-05 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmCore', '0069_groupcrmmessage'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcrmmessage',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='groupcrmmessage',
            name='message_type',
            field=models.CharField(blank=True, choices=[('text', 'TEXT'), ('notification', 'NOTIFICATION')], default='text', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='groupcrmmessage',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
